language: node_js
sudo: true
node_js: 4
script:
- npm run lint
- npm test
env:
  global:
  - CF_APP=social-customer-care-stage
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=WatsonPlatformServices
  - CF_SPACE=appgallery
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
    - cf-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/social-customer-care
  skip_cleanup: true